@url = http://localhost:5000/

# Product Item Routes
get {{url}}product

###
get {{url}}product/1

###
post {{url}}product
Content-Type: application/json
 
{
"name": "große Seifenschale",
"categoryId": 3,
"color": "blau",
"price": 8,
"image": "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExbTlpZDFlbWF1czQ5eGh5aXdhdm95ZHh2Y2p1azMwbnJmN202aXQ0ZiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/Vj8muG9sIBayobsTcU/giphy.gif"
}

###
put {{url}}product/1
Content-Type: application/json

{"name": "Schale"}

###
delete {{url}}product/1

# Cart Routes
###
get {{url}}cart/1

###
post {{url}}cart

###
post {{url}}cartitem
Content-Type: application/json
 
{"productId": 2, "quantity": 1, "cartId": 1}

# Cart Item Routes
###
put {{url}}cartitem/4
Content-Type: application/json

{"quantity": 2}

###
delete {{url}}cartitem/5

# Category Item Routes
###
post {{url}}category
Content-Type: application/json
 
{"name": "Seifenschale"}

###
get {{url}}category

###
delete {{url}}category/2